# Generated by Django 5.2.15 on 2026-06-13 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('series', models.CharField(max_length=255)),
                ('printed_total', models.IntegerField()),
                ('total', models.IntegerField()),
                ('ptcgo_code', models.CharField(blank=True, max_length=20)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('updated_at_api', models.DateTimeField(blank=True, null=True)),
                ('legalities', models.JSONField(default=dict)),
                ('images', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'set',
                'verbose_name_plural': 'sets',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('supertype', models.CharField(max_length=50)),
                ('subtypes', models.JSONField(default=list)),
                ('hp', models.CharField(blank=True, max_length=10)),
                ('types', models.JSONField(default=list)),
                ('evolves_from', models.CharField(blank=True, max_length=255)),
                ('attacks', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('resistances', models.JSONField(default=list)),
                ('retreat_cost', models.JSONField(default=list)),
                ('converted_retreat_cost', models.IntegerField(blank=True, null=True)),
                ('number', models.CharField(max_length=20)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('rarity', models.CharField(blank=True, max_length=100)),
                ('flavor_text', models.TextField(blank=True)),
                ('national_pokedex_numbers', models.JSONField(default=list)),
                ('legalities', models.JSONField(default=dict)),
                ('images', models.JSONField(default=dict)),
                ('tcgplayer', models.JSONField(blank=True, null=True)),
                ('cardmarket', models.JSONField(blank=True, null=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.cardset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
