# Generated by Django 5.2.15 on 2026-06-13 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardset',
            options={'ordering': ['-release_date', 'name'], 'verbose_name': 'set', 'verbose_name_plural': 'sets'},
        ),
    ]
