# Generated by Django 5.2.15 on 2026-06-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_cardset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='abilities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='ancient_trait',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='evolves_to',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='card',
            name='level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='regulation_mark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='rules',
            field=models.JSONField(default=list),
        ),
    ]
