# Generated by Django 5.2.15 on 2026-06-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0002_collectionitempurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
